### ISSUE TITLE
Training on multiple GPUs fails with  TF 1.4.0

### ISSUE THREAD

**Issue by JonathanCMitchell** [matterport/Mask_RCNN#511]
Hi there, 

When training on multiple GPUs with the latest master branch, fails with Tensorflow 1.4.0. There is a zero division going on when we have parallel model. Has anybody tested this with TF  <= 1.4.0 ?

**Comment by YubinXie** [comment]
Recently updates cause an error on multiple GPU. Version below 1.4 gives zero division error and version above 1.4 directly killed my kernel... in py36. 

I plan to down-grade to 1.4 and use single GPU. I have spent too much time on this error but still no way to fix it.

**Comment by JonathanCMitchell** [comment]
With Tensorflow 1.7, I simply ran the parallel_model.py file and I got this.
```
Traceback (most recent call last):
  File "mrcnn/parallel_model.py", line 161, in <module>
    model = ParallelModel(model, GPU_COUNT)
  File "mrcnn/parallel_model.py", line 35, in __init__
    self.inner_model = keras_model
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/engine/network.py", line 317, in __setattr__
RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super(YourClass, self).__init__()`. Always start with this line.
```
Environment: 
Tensorflow 1.7.0
Keras: 2.1.6

**Comment by ericj974** [comment]
@JonathanCMitchell Are you sure to have updated your code ? Last commit on branch master, before your post, would throw an error with tf  version = 1.4 (keep_dims replaced by keepdims for reduce_mean functions and this is not recognized by tf 1.4). I suggest you update your tf lib to >= 1.6 and try again. @waleedka I guess `requirements.txt` has to be updated to reflect this.

**Comment by nemonameless** [comment]
@ericj974 Do you mean that tf version >= 1.6 can run on 4 GPUs  parallel_model and no bug?

**Comment by ericj974** [comment]
@nemonameless I mean that at least no error is thrown. But I observe some (serious) performance issues when using more than one GPU.

**Comment by ericj974** [comment]
@nemonameless I mean that at least no error is thrown. But I observe some (serious) performance issues when using more than one GPU.

**Comment by ouyangkid** [comment]
@JonathanCMitchell I modified my environment (degrade the keras=2.2.0 to keras=2.1.6), however, another error came out as follows:

Traceback (most recent call last):
  File "balloon.py", line 362, in <module>
    video_path=args.video)
  File "balloon.py", line 227, in detect_and_color_splash
    r = model.detect([image], verbose=1)[0]
  File "/home/zfserver/anaconda2/envs/py34/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/model.py", line 2475, in detect
**AssertionError: len(images) must be equal to BATCH_SIZE**

**Comment by ericj974** [comment]
Multi gpu issue may have been solved on my side (see PR #706 ). In short, model creation has to be done on the cpu first.

**Comment by drsxr** [comment]
Also getting the:
 RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super(YourClass, self).__init__()`. Always start with this line.
When I try to do multi-gpu (GPU=2 and I have 2 GPU's). 
Works fine with model set to 1 GPU.
TF-gpu ==1.8
Keras==2.2 (changed topology to saving in model.py as per other thread on this issue to get to run)

**Comment by patrickcgray** [comment]
I'm getting this same error. It also began working for me once I set it to 1 GPU even though I have two available and a couple weeks ago it was working fine on both.

**Comment by ericj974** [comment]
@patrickcgray @drsxr Could you (1) setup conda and the same env as [here (cpu)](https://github.com/ericj974/Mask_RCNN/blob/master/environment-cpu.yml) or [here (gpu)](https://github.com/ericj974/Mask_RCNN/blob/master/environment-gpu.yml), (2) try to run [this script](https://github.com/ericj974/Mask_RCNN/blob/master/scripts/train_shapes.py) ?

**Comment by zqn187** [comment]
@ouyangkid Hello! Is your problem solved?（AssertionError: len(images) must be equal to BATCH_SIZE）

**Comment by ouyangkid** [comment]
@zqn187 If you set classes=None, which means using all the data for val, everything works well.
However, if you set a special class=person, or several classes==['class1','class2'], it come up this problem.

**Comment by drsxr** [comment]
@ericj974 Eric, I'm seeing behaviour that is not specific to your build - I think it has something to do with Keras and Multi-GPU, as Keras' behaviour with multi-GPU is pretty hinky for me (& others too).  Let's see what happens with further updates.

**Comment by spMohanty** [comment]
A **temporary fix** is to downgrade to keras2.1.3 with : 
```
pip install keras==2.1.3
```

**Comment by asimay** [comment]
hi, I encounter the same problem, my keras version :2.2.2, if downgrade to 2.1.3, the problem solved.
`pip install keras==2.1.3`

**Comment by asimay** [comment]
AssertionError: len(images) must be equal to BATCH_SIZE
this is caused by your detect() function, in demo detect() only receive 1 image, but if you use multi GPU, you need to feed more image into detect(),
