### ISSUE TITLE
Visualize Activations

### ISSUE THREAD

**Issue by amin3511** [matterport/Mask_RCNN#934]
hi everyone 
i run inspect_balloon_model.ipynb but in the Visualize Activations section, i get this error:
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-36-8bd731e4a663> in <module>()
      6     ("res4w_out",          model.keras_model.get_layer("res4w_out").output),  # for resnet100
      7     ("rpn_bbox",           model.keras_model.get_layer("rpn_bbox").output),
----> 8     ("roi",                model.keras_model.get_layer("ROI").output),
      9 ])

~/Downloads/Mask_RCNN/mrcnn/model.py in run_graph(self, images, outputs, image_metas)
   2687         if model.uses_learning_phase and not isinstance(K.learning_phase(), int):
   2688             model_in.append(0.)
-> 2689         outputs_np = kf(model_in)
   2690 
   2691         # Pack the generated Numpy arrays into a a dict and log the results.

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2659                 return self._legacy_call(inputs)
   2660 
-> 2661             return self._call(inputs)
   2662         else:
   2663             if py_any(is_tensor(x) for x in inputs):

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2628                                 feed_symbols,
   2629                                 symbol_vals,
-> 2630                                 session)
   2631         fetched = self._callable_fn(*array_vals)
   2632         return fetched[:len(self.outputs)]

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   2580         callable_opts.target.append(self.updates_op.name)
   2581         # Create callable.
-> 2582         callable_fn = session._make_callable_from_options(callable_opts)
   2583         # Cache parameters corresponding to the generated callable, so that
   2584         # we can detect future mismatches and refresh the callable.

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py in _make_callable_from_options(self, callable_options)
   1478     """
   1479     self._extend_graph()
-> 1480     return BaseSession._Callable(self, callable_options)
   1481 
   1482 

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py in __init__(self, session, callable_options)
   1439           else:
   1440             self._handle = tf_session.TF_DeprecatedSessionMakeCallable(
-> 1441                 session._session, options_ptr, status)
   1442       finally:
   1443         tf_session.TF_DeleteBuffer(options_ptr)

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: input_image:0 is both fed and fetched.
how can i solve it?

**Comment by csyang6052** [comment]
I have the same issue -

http://localhost:8888/notebooks/mask_rcnn/inspect_balloon_model.ipynb

# Get activations of a few sample layers
activations = model.run_graph([image], [
    ("input_image",        model.keras_model.get_layer("input_image").output),
    ("res2c_out",          model.keras_model.get_layer("res2c_out").output),
    ("res3c_out",          model.keras_model.get_layer("res3c_out").output),
    ("res4w_out",          model.keras_model.get_layer("res4w_out").output),  # for resnet100
    ("rpn_bbox",           model.keras_model.get_layer("rpn_bbox").output),
    ("roi",                model.keras_model.get_layer("ROI").output),
])

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-55-8bd731e4a663> in <module>()
      6     ("res4w_out",          model.keras_model.get_layer("res4w_out").output),  # for resnet100
      7     ("rpn_bbox",           model.keras_model.get_layer("rpn_bbox").output),
----> 8     ("roi",                model.keras_model.get_layer("ROI").output),
      9 ])

~/mask_rcnn/mrcnn/model.py in run_graph(self, images, outputs, image_metas)
   2716         if model.uses_learning_phase and not isinstance(K.learning_phase(), int):
   2717             model_in.append(0.)
-> 2718         outputs_np = kf(model_in)
   2719 
   2720         # Pack the generated Numpy arrays into a a dict and log the results.

~/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2664                 return self._legacy_call(inputs)
   2665 
-> 2666             return self._call(inputs)
   2667         else:
   2668             if py_any(is_tensor(x) for x in inputs):

~/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2633                                 feed_symbols,
   2634                                 symbol_vals,
-> 2635                                 session)
   2636         fetched = self._callable_fn(*array_vals)
   2637         return fetched[:len(self.outputs)]

~/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   2585         callable_opts.target.append(self.updates_op.name)
   2586         # Create callable.
-> 2587         callable_fn = session._make_callable_from_options(callable_opts)
   2588         # Cache parameters corresponding to the generated callable, so that
   2589         # we can detect future mismatches and refresh the callable.

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _make_callable_from_options(self, callable_options)
   1412     """
   1413     self._extend_graph()
-> 1414     return BaseSession._Callable(self, callable_options)
   1415 
   1416 

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in __init__(self, session, callable_options)
   1366         with errors.raise_exception_on_not_ok_status() as status:
   1367           self._handle = tf_session.TF_SessionMakeCallable(
-> 1368               session._session, options_ptr, status)
   1369       finally:
   1370         tf_session.TF_DeleteBuffer(options_ptr)

~/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: input_image:0 is both fed and fetched.

**Comment by csyang6052** [comment]
According to https://github.com/matterport/Mask_RCNN/issues/803
The issue solved with python 3.6.6 (my case).

**Comment by lina1996Alice** [comment]
i also meet the same.can you give the details of operation? i also use the python 3,but the question still exist

**Comment by Su-deep** [comment]
Hi guys I have the same issue as well, I am using tensorflow-gpu1.11.0 and I have python 3.6.6 installed .
I think this issue is related with the version of tensorflow since the issue resolves itself if older version of tensorflow is used( Like in issue #803)

Please let me know if there's a solution where I don't have to roll back to older version of tensorflow

![image](https://user-images.githubusercontent.com/12501565/47174601-4951e580-d2ce-11e8-9b1e-e181b863cf3d.png)

**Comment by Su-deep** [comment]
Reverting back to older version of tensorflow from 1.11.0 to 1.5.0 fixed the problem, but still not sure why the issue is caused in first place(has to do with how keras uses tensorflow in the backend)
![image](https://user-images.githubusercontent.com/12501565/47188012-82508100-d2f3-11e8-9b93-58caad8b21c0.png)

**Comment by waleedka** [comment]
I just merged @keineahnung2345 's PR that fixes this issue.
